### PR TITLE
Feature/file structure dev

### PR DESCRIPTION
**Pull request by danhugs**

### CODE REVIEW

**Comment by danhugs** [comment]
@RemyaTP 
I think we need to strip out **all** unrelated legacy files.  This is all far too advanced for what we're building here.

We do not need:

- Any files related to the DKS
- Any files relating to the custom image model
- Any files relating to legacy KIC/HIC file structure (left-right enums, Timestep?)
- Any files relating to existing AnatomicalMeasurements.  This should use the new Measurement Manager being developed by Jijeesh.

**Comment by KICO-SOURCE** [comment]
@RemyaTP 
Can you please provide some justification for keeping SensitivityResults / AnatomicalMeasurements - how do these relate to being able to load and populate a patient data object?  

These both appear to be supporting legacy data.  Anatomical Measurements will all be taken in-platform; this should not yet be loaded from a KIC or a HIC.
 
Additionally, you appear to have imported BaseProject directly from IPS, and this is explicitly not what we want to do.  This is filled with legacy code, and will create a gigantic amount of technical debt very quickly.  A reminder that the reason we are doing this project is to get away from the structure of our legacy code, and the technical debt that this introduced.  

**We need to avoid legacy code.**

**Comment by RemyaTP** [comment]
@KICO-SOURCE @lpug21 Almost all legacy code including SensitivityResults,  BaseProject and legacy enums are removed now.

About AnatomicalMeasurements, that class required to hold data  from FunctionalValues tag in the shared HIC file, If that tag is no longer relevant we can remove that class too.
DataEncryption class is kept for now, to decrypt the hic/kic file.
Also some methods from MeshGeometryFunctions from the legacy source copied to new source to parse the mesh data from the hic/kic file.

**Comment by RemyaTP** [comment]
@lpug21 @KICO-SOURCE Removed legacy class AnatomicalMeasurements, keeping the FunctionalValues from hic file.

**Comment by KICO-SOURCE** [comment]
Looking good Remya.  Ready for a merge?

**Pull request merged**
